### ISSUE TITLE
Doesn't Run

### ISSUE THREAD

**Issue by abertman** [nicholasRenninger/Renninger_CSCI2270_FinalProject#2]
I couldn't make it run in its native directory, on codeblocks, geany or even just from command line. Perhaps update the readme to be more clear?

**Comment by nicholasRenninger** [comment]
@abertman Everything is updated. I added a lot of information about how to run it. You should be able to run it in Geany, as that is what I use, as long as you use the *.cpp compiler setting in Geany. What OS are you running?

**Comment by nicholasRenninger** [comment]
Also, please make sure to re-download my repository, I made several changes to the printing and such to make it easier to read, and I fixed a small bug.

**Comment by nicholasRenninger** [comment]
@abertman Also, please make sure to re-download my repository, I made several changes to the printing and such to make it easier to read, and I fixed a small bug.
